### ISSUE TITLE
Matmul panic on Cuda (pre-Ampere)

### ISSUE THREAD

**Issue by swfsql** [tracel-ai/burn#4066]
**Describe the bug**
A matmul operation panics when running on cuda, with the following error:
```
Unable to launch matmul because a required feature is unavailable: Types lhs=Scalar(Float(TF32)), rhs=Scalar(Float(TF32)) and/or output=Scalar(Float(F32)) not supported.
```
I confirmed that both current main (2025-11-25) and 0.20.0-pre.3 panic for the given example.

**To Reproduce**
```toml
[dependencies.burn]
git = "https://github.com/tracel-ai/burn.git"
# 2025-11-25 main
rev = "080ade2b82421fd16058a6cfb6e6d54ecb7f4b41"
default-features = false
```

```rust
use burn::prelude::*;

type NdArray = burn::backend::NdArray<f32, i32>;
type Cuda = burn::backend::Cuda<f32, i32>;

fn main() {
    println!("infer ndarray");
    infer::<NdArray>();
    println!("infer cuda");
    infer::<Cuda>();
}

pub fn infer<B: Backend>() {
    let device = <B::Device>::default();
    let a: Tensor<B, 2> = Tensor::from_floats([[1., 2.], [3., 4.]], &device);
    let b: Tensor<B, 2> = Tensor::from_floats([[5., 6.], [7., 8.]], &device);
    let _loss = b.matmul(a).sum();
}
```

**Expected behavior**
Pass run (no panics).

**Desktop:**
 - OS: Linux 6.x
 - Device: NVIDIA GeForce RTX 2060
 - Cuda Version: 12.2

**Additional context**

- Nathaniel, on discord, noted that:
  - This is device-specific as this couldn't get reproduced; My gpu is from 2018, pre-ampere from 2020 (which added tf32).
  - This works correctly in fp16.
- Output and Backtrace
```
infer ndarray
infer cuda

thread 'main' (32780) panicked at (...)/cubecl-matmul/src/base.rs:542:26:
called `Result::unwrap()` on an `Err` value: Unable to launch matmul because a required feature is unavailable: Types lhs=Scalar(Float(TF32)), rhs=Scalar(Float(TF32)) and/or output=Scalar(Float(F32)) not supported.


stack backtrace:
   (...)
   4: cubecl_matmul::base::launch_ref
             at (...)/cubecl-matmul/src/base.rs:542:26
   5: burn_cubecl::kernel::matmul::base::launch_matmul
             at (...)/burn-cubecl/src/kernel/matmul/base.rs:102:5
   6: burn_cubecl::kernel::matmul::base::matmul
             at (...)/burn-cubecl/src/kernel/matmul/base.rs:43:13
   7: burn_cubecl::ops::float_ops::<impl burn_tensor::tensor::ops::tensor::FloatTensorOps<burn_cubecl::backend::CubeBackend<R,F,I,BT>> for burn_cubecl::backend::CubeBackend<R,F,I,BT>>::float_matmul
             at (...)/burn-cubecl/src/ops/float_ops.rs:144:9
   8: <burn_tensor::tensor::api::kind::Float as burn_tensor::tensor::api::numeric::Numeric<B>>::matmul
             at (...)/burn-tensor/src/tensor/api/numeric.rs:4339:40
   9: burn_tensor::tensor::api::numeric::<impl burn_tensor::tensor::api::base::Tensor<B,_,K>>::matmul
             at (...)/burn-tensor/src/tensor/api/numeric.rs:2321:21
  10: burn_bug::infer
             at ./src/main.rs:17:19
  11: burn_bug::main
             at ./src/main.rs:10:5
  (...)
```

**Comment by nathanielsimard** [comment]
Is the bug fixed with the new error handling strategy from cubecl ? https://github.com/tracel-ai/burn/pull/4076 Don't forget to cleanup the autotune cache before testing

**Comment by swfsql** [comment]
@nathanielsimard I ran a cargo clean and update before a run, using burn `19db09c9`, and then I got this compilation error:

```
error[E0615]: attempted to take value of method `into` on type `&'static str`
   --> (...)/cubecl-cuda/src/compute/server.rs:371:96
    |
371 |                         context: "CUDA version 12.8 required for tensor map format Im2colWide".into,
    |                                                                                                ^^^^ method, not a field
    |
help: use parentheses to call the method
    |
371 |                         context: "CUDA version 12.8 required for tensor map format Im2colWide".into(),
    | 
```

---

Edit: I've locally fixed that error (just added the `()`) and tested again, but I'm still getting the same error on burn 2025-11-29 `b598397c`:
```
infer ndarray
infer cuda

thread 'main' (10677) panicked at (...)/cubecl-matmul/src/base.rs:700:26:
called `Result::unwrap()` on an `Err` value: Unable to launch matmul because a required feature is unavailable: Types lhs=Scalar(Float(TF32)), rhs=Scalar(Float(TF32)) and/or output=Scalar(Float(F32)) not supported.


stack backtrace:
   (...)
   4: cubecl_matmul::base::launch_ref
             at (...)/cubecl-matmul/src/base.rs:700:26
   5: burn_cubecl::kernel::matmul::base::launch_matmul
             at (...)/burn-cubecl/src/kernel/matmul/base.rs:102:5
   6: burn_cubecl::kernel::matmul::base::matmul
             at (...)/burn-cubecl/src/kernel/matmul/base.rs:43:13
   7: burn_cubecl::ops::float_ops::<impl burn_tensor::tensor::ops::tensor::FloatTensorOps<burn_cubecl::backend::CubeBackend<R,F,I,BT>> for burn_cubecl::backend::CubeBackend<R,F,I,BT>>::float_matmul
             at (...)/burn-cubecl/src/ops/float_ops.rs:145:9
   8: <burn_tensor::tensor::api::kind::Float as burn_tensor::tensor::api::numeric::Numeric<B>>::matmul
             at (...)/burn-tensor/src/tensor/api/numeric.rs:4339:40
   9: burn_tensor::tensor::api::numeric::<impl burn_tensor::tensor::api::base::Tensor<B,_,K>>::matmul
             at (...)/burn-tensor/src/tensor/api/numeric.rs:2321:21
```

**Comment by nathanielsimard** [comment]
It's fixed on main

**Comment by nathanielsimard** [comment]
Well the compilation is fixed on main, but not the main error. From the backtrace I guess you're not using autotune?

**Comment by swfsql** [comment]
Thanks @nathanielsimard, the issue is now solved for main, both with or without autotune. Just checked after a cargo clean. Thx!

Edit:
> (...) Don't forget to cleanup the autotune cache before testing

Just a curiosity, is the autotune cache under `target/`? If so it is cleaned up with a cargo clean?

**Comment by swfsql** [comment]
Hi, just an update, this problem currently occurs (`main` @ `9a34a52f`) if the autotune is *off*. If the autotune is *on*, the it runs ok.

Backtrace:
```
thread 'main' (21481) panicked at (...)/cubek-matmul/src/launch/base.rs:484:26:
called `Result::unwrap()` on an `Err` value: Unable to launch matmul because a required feature is unavailable: Types lhs=Scalar(Float(TF32)), rhs=Scalar(Float(TF32)) and/or output=Scalar(Float(F32)) not supported.


stack backtrace:
   (...)
   4: cubek_matmul::launch::base::launch_ref
             at (...)/cubek-matmul/src/launch/base.rs:484:26
   5: burn_cubecl::kernel::matmul::base::launch_matmul
             at (...)/burn-cubecl/src/kernel/matmul/base.rs:122:5
   6: burn_cubecl::kernel::matmul::base::matmul
             at (...)/burn-cubecl/src/kernel/matmul/base.rs:43:13
   7: burn_cubecl::ops::float_ops::<impl burn_backend::backend::ops::tensor::FloatTensorOps<burn_cubecl::backend::CubeBackend<R,F,I,BT>> for burn_cubecl::backend::CubeBackend<R,F,I,BT>>::float_matmul
             at (...)/burn-cubecl/src/ops/float_ops.rs:157:9
   8: burn_backend::tensor::ops::float::<impl burn_backend::tensor::ops::numeric::Numeric<B> for burn_backend::tensor::kind::Float>::matmul
             at (...)/burn-backend/src/tensor/ops/float.rs:694:40
   9: burn_tensor::tensor::api::numeric::<impl burn_tensor::tensor::api::base::Tensor<B,_,K>>::matmul
             at (...)/burn-tensor/src/tensor/api/numeric.rs:2079:21
   (...)
```

**Comment by nathanielsimard** [comment]
> Hi, just an update, this problem currently occurs (`main` @ `9a34a52f`) if the autotune is _off_. If the autotune is _on_, the it runs ok.

Error handling at the jit compilation level is mostly done with the help of autotune, so this is expected. The matmul selector without autotune is very basic and might not cover the necessary algorithms to run on all hardware.

**Comment by swfsql** [comment]
Hi, the example now runs successfully on `0.20.0` and newer! Thanks a lot!
